import { SpellConfig } from '../types';

export const SPELLS: Record<string, SpellConfig> = {
  pyro_blast: {
    id: 'pyro_blast',
    name: 'Pyro Blast',
    description: 'Fast, piercing fiery bolt. Low mana cost and high fire rate.',
    manaCost: 10,
    cooldownMs: 220,
    speed: 65,
    damage: 40,
    splashRadius: 3.2,
    color: '#ff6600',
    emissiveColor: '#ff8800',
    iconName: 'Flame',
  },
  inferno_orb: {
    id: 'inferno_orb',
    name: 'Inferno Orb',
    description: 'Hold to charge a cataclysmic sphere of pure solar flame.',
    manaCost: 35,
    cooldownMs: 700,
    speed: 40,
    damage: 160,
    splashRadius: 8.5,
    chargeable: true,
    maxChargeTimeMs: 1600,
    color: '#ff2200',
    emissiveColor: '#ffaa00',
    iconName: 'Sun',
  },
  flame_triad: {
    id: 'flame_triad',
    name: 'Flame Triad',
    description: 'Launches a 3-way spread of flaming bolts to clear hordes.',
    manaCost: 22,
    cooldownMs: 400,
    speed: 55,
    damage: 32,
    splashRadius: 3.0,
    color: '#ffaa00',
    emissiveColor: '#ffff44',
    iconName: 'Sparkles',
  },
  meteor_strike: {
    id: 'meteor_strike',
    name: 'Meteor Strike',
    description: 'Heavy lobbed pyromancy bomb with arc physics and huge impact blast.',
    manaCost: 45,
    cooldownMs: 900,
    speed: 45,
    damage: 220,
    splashRadius: 9.0,
    color: '#ff1100',
    emissiveColor: '#ff4400',
    iconName: 'Bomb',
  },
};
